version: '3.1'

services:

  dev_db:
    image: postgres
    restart: always
    container_name: pipeline_db_container
    environment:
      POSTGRES_DB: pipeline_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    # 'bridge' is the default for docker run, but docker-compose requires it explicitly
    network_mode: "bridge" 
    ports:
      - 5433:5432 # out:in

  adminer:
    image: adminer
    restart: always
    container_name: adminer_container
    ports:
      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    # note that these two environment variables are required
    environment:
      PGADMIN_DEFAULT_EMAIL: keith.chev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    network_mode: "bridge"
    ports:
      - 8081:80
